package msgp

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *Identity) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 7
	// string "0"
	o = append(o, 0x87, 0xa1, 0x30)
	o = msgp.AppendString(o, z.Policy)
	// string "1"
	o = append(o, 0xa1, 0x31)
	o = msgp.AppendBool(o, z.IsAdmin)
	// string "2"
	o = append(o, 0xa1, 0x32)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Children)))
	for za0001 := range z.Children {
		o = msgp.AppendString(o, z.Children[za0001])
	}
	// string "3"
	o = append(o, 0xa1, 0x33)
	o = msgp.AppendDuration(o, z.TTL)
	// string "4"
	o = append(o, 0xa1, 0x34)
	o = msgp.AppendTime(o, z.ExpiresAt)
	// string "5"
	o = append(o, 0xa1, 0x35)
	o = msgp.AppendTime(o, z.CreatedAt)
	// string "6"
	o = append(o, 0xa1, 0x36)
	o = msgp.AppendString(o, z.CreatedBy)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Identity) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "0":
			z.Policy, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Policy")
				return
			}
		case "1":
			z.IsAdmin, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsAdmin")
				return
			}
		case "2":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Children")
				return
			}
			if cap(z.Children) >= int(zb0002) {
				z.Children = (z.Children)[:zb0002]
			} else {
				z.Children = make([]string, zb0002)
			}
			for za0001 := range z.Children {
				z.Children[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Children", za0001)
					return
				}
			}
		case "3":
			z.TTL, bts, err = msgp.ReadDurationBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TTL")
				return
			}
		case "4":
			z.ExpiresAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ExpiresAt")
				return
			}
		case "5":
			z.CreatedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "6":
			z.CreatedBy, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedBy")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Identity) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.Policy) + 2 + msgp.BoolSize + 2 + msgp.ArrayHeaderSize
	for za0001 := range z.Children {
		s += msgp.StringPrefixSize + len(z.Children[za0001])
	}
	s += 2 + msgp.DurationSize + 2 + msgp.TimeSize + 2 + msgp.TimeSize + 2 + msgp.StringPrefixSize + len(z.CreatedBy)
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *Policy) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 4
	// string "0"
	o = append(o, 0x84, 0xa1, 0x30)
	o = msgp.AppendMapHeader(o, uint32(len(z.Allow)))
	for za0001 := range z.Allow {
		o = msgp.AppendString(o, za0001)
		// map header, size 0
		o = append(o, 0x80)
	}
	// string "1"
	o = append(o, 0xa1, 0x31)
	o = msgp.AppendMapHeader(o, uint32(len(z.Deny)))
	for za0003 := range z.Deny {
		o = msgp.AppendString(o, za0003)
		// map header, size 0
		o = append(o, 0x80)
	}
	// string "2"
	o = append(o, 0xa1, 0x32)
	o = msgp.AppendTime(o, z.CreatedAt)
	// string "3"
	o = append(o, 0xa1, 0x33)
	o = msgp.AppendString(o, z.CreatedBy)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Policy) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "0":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Allow")
				return
			}
			if z.Allow == nil {
				z.Allow = make(map[string]struct{}, zb0002)
			} else if len(z.Allow) > 0 {
				for key := range z.Allow {
					delete(z.Allow, key)
				}
			}
			for zb0002 > 0 {
				var za0001 string
				var za0002 struct{}
				zb0002--
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Allow")
					return
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Allow", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Allow", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Allow", za0001)
							return
						}
					}
				}
				z.Allow[za0001] = za0002
			}
		case "1":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Deny")
				return
			}
			if z.Deny == nil {
				z.Deny = make(map[string]struct{}, zb0004)
			} else if len(z.Deny) > 0 {
				for key := range z.Deny {
					delete(z.Deny, key)
				}
			}
			for zb0004 > 0 {
				var za0003 string
				var za0004 struct{}
				zb0004--
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Deny")
					return
				}
				var zb0005 uint32
				zb0005, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Deny", za0003)
					return
				}
				for zb0005 > 0 {
					zb0005--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Deny", za0003)
						return
					}
					switch msgp.UnsafeString(field) {
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Deny", za0003)
							return
						}
					}
				}
				z.Deny[za0003] = za0004
			}
		case "2":
			z.CreatedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedAt")
				return
			}
		case "3":
			z.CreatedBy, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "CreatedBy")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Policy) Msgsize() (s int) {
	s = 1 + 2 + msgp.MapHeaderSize
	if z.Allow != nil {
		for za0001, za0002 := range z.Allow {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + 1
		}
	}
	s += 2 + msgp.MapHeaderSize
	if z.Deny != nil {
		for za0003, za0004 := range z.Deny {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + 1
		}
	}
	s += 2 + msgp.TimeSize + 2 + msgp.StringPrefixSize + len(z.CreatedBy)
	return
}
