linters-settings:
  gofumpt:
    simplify: true

  misspell:
    locale: US

  staticcheck:
    checks: ["all", "-SA1019"]

linters:
  disable-all: true
  enable:
    - durationcheck
    - gocritic
    - gofumpt
    - goimports
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - tenv
    - typecheck
    - unconvert
    - unused

issues:
  exclude-use-default: false
  exclude:
      - "var-naming: don't use ALL_CAPS in Go names; use CamelCase"
      - "package-comments: should have a package comment"
      - "exitAfterDefer:"

service:
  golangci-lint-version: 1.57.2 # use the fixed version to not introduce new linters unexpectedly
