linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gosimple
    - deadcode
    - unused
    - structcheck
    - prealloc
    - unconvert
    - gofumpt

issues:
  exclude-use-default: false
  exclude:
      - error strings should not be capitalized or end with punctuation or a newline
      - should have comment           # TODO(aead): Remove once all exported ident. have comments!

service:
  golangci-lint-version: 1.43.0 # use the fixed version to not introduce new linters unexpectedly
