linters-settings:
  misspell:
    locale: US

  staticcheck:
    checks: ["all", "-SA1019"]

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - staticcheck
    - govet
    - revive
    - ineffassign
    - gosimple
    - unused
    - prealloc
    - unconvert
    - gofumpt

issues:
  exclude-use-default: false
  exclude:
      - "var-naming: don't use ALL_CAPS in Go names; use CamelCase"
      - "package-comments: should have a package comment"
      - "exitAfterDefer:"
