project_name: kes

release:
   name_template: Release {{ replace .CommitDate ":" "-" }}

   github:
    owner: minio
    name: kes

before:
  hooks:
    - go mod tidy
    - sh -c 'git diff --quiet || (echo "Repo contains modified files. Run git checkout" && exit 1)'

builds:
  -
    main: ./cmd/kes
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -buildvcs=true
    ldflags:
      - "-s -w"

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

nfpms:
  -
    vendor: MinIO, Inc.
    homepage: https://github.com/minio/kes
    maintainer: MinIO Development <dev@min.io>
    description: KES is a stateless and distributed key-management system for high-performance applications
    license: GNU Affero General Public License v3.0
    formats:
      - deb
      - rpm

signs:
  -
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - '-c'
      - 'minisign -s /media/${USER}/minio/minisign.key -Sm ${artifact} < /media/${USER}/minio/minisign-passphrase'
    artifacts: all

snapshot:
  name_template: '{{ replace .CommitDate ":" "-" }}'

changelog:
  sort: asc

dockers:
- image_templates:
  - minio/kes:{{ replace .CommitDate ":" "-" }}-amd64
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/amd64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - minio/kes:{{ replace .CommitDate ":" "-" }}-ppc64le
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/ppc64le'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - minio/kes:{{ replace .CommitDate ":" "-" }}-s390x
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/s390x'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - minio/kes:{{ replace .CommitDate ":" "-" }}-arm64
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/arm64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-amd64
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/amd64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-ppc64le
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/ppc64le'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-s390x
  use: buildx
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/s390x'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
- image_templates:
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-arm64
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile.release
  extra_files:
    - LICENSE
    - CREDITS
  build_flag_templates:
  - '--platform=linux/arm64'
  - '--build-arg=TAG={{ replace .CommitDate ":" "-" }}'
docker_manifests:
- name_template: minio/kes:{{ replace .CommitDate ":" "-" }}
  image_templates:
  - minio/kes:{{ replace .CommitDate ":" "-" }}-amd64
  - minio/kes:{{ replace .CommitDate ":" "-" }}-arm64
  - minio/kes:{{ replace .CommitDate ":" "-" }}-ppc64le
  - minio/kes:{{ replace .CommitDate ":" "-" }}-s390x
- name_template: quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}
  image_templates:
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-amd64
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-arm64
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-ppc64le
  - quay.io/minio/kes:{{ replace .CommitDate ":" "-" }}-s390x
- name_template: minio/kes:latest
  image_templates:
  - minio/kes:{{ replace .CommitDate ":" "-" }}-amd64
  - minio/kes:{{ replace .CommitDate ":" "-" }}-arm64
  - minio/kes:{{ replace .CommitDate ":" "-" }}-ppc64le
  - minio/kes:{{ replace .CommitDate ":" "-" }}-s390x
