project_name: kes

release:
   name_template: "Version {{.Version}}"

   github:
    owner: minio
    name: kes

before:
  hooks:
    - go mod tidy

builds:
  -
    main: ./cmd/kes
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}}"

archives:
  -
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary
    replacements:
      arm: arm

signs:
  -
    signature: "${artifact}.minisig"
    cmd: "sh"
    args:
      - '-c'
      - 'minisign -s /media/${USER}/minio/minisign.key -Sm ${artifact} < /media/${USER}/minio/minisign-passphrase'
    artifacts: all

snapshot:
  name_template: v0.0.0@{{.ShortCommit}}

changelog:
  sort: asc

dockers:
  -
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile.release
    image_templates:
      - minio/kes:{{ .Tag }}
      - minio/kes:latest
