// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "ws"
  ],
  "swagger": "2.0",
  "info": {
    "title": "MinIO KES",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/encryption/apis": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption apis",
        "operationId": "APIs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionAPIsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/describe-self/identity": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe self identity",
        "operationId": "DescribeSelfIdentity",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribeSelfIdentityResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/identities": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption list identities",
        "operationId": "ListIdentities",
        "parameters": [
          {
            "type": "string",
            "description": "pattern to retrieve identities",
            "name": "pattern",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionListIdentitiesResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/identities/{name}": {
      "delete": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption delete identity",
        "operationId": "DeleteIdentity",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption identity name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/identities/{name}/describe": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe identity",
        "operationId": "DescribeIdentity",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption identity name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribeIdentityResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/keys": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption list keys",
        "operationId": "ListKeys",
        "parameters": [
          {
            "type": "string",
            "description": "pattern to retrieve keys",
            "name": "pattern",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionListKeysResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption create key",
        "operationId": "CreateKey",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionCreateKeyRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/keys/{name}": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe key",
        "operationId": "DescribeKey",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption key name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribeKeyResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption delete key",
        "operationId": "DeleteKey",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption key name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/keys/{name}/import": {
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption import key",
        "operationId": "ImportKey",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionImportKeyRequest"
            }
          },
          {
            "type": "string",
            "description": "Encryption key name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/metrics": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption metrics",
        "operationId": "Metrics",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionMetricsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption list policies",
        "operationId": "ListPolicies",
        "parameters": [
          {
            "type": "string",
            "description": "pattern to retrieve policies",
            "name": "pattern",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionListPoliciesResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption set policy",
        "operationId": "SetPolicy",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionSetPolicyRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies/{name}": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption get policy",
        "operationId": "GetPolicy",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionGetPolicyResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption delete policy",
        "operationId": "DeletePolicy",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies/{name}/assign": {
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption assign policy",
        "operationId": "AssignPolicy",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionAssignPolicyRequest"
            }
          },
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies/{name}/describe": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe policy",
        "operationId": "DescribePolicy",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribePolicyResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/status": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption status",
        "operationId": "Status",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionStatusResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/version": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption version",
        "operationId": "Version",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionVersionResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/login": {
      "get": {
        "security": [],
        "tags": [
          "Auth"
        ],
        "summary": "Returns login strategy, form or sso.",
        "operationId": "LoginDetail",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/loginDetails"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "Auth"
        ],
        "summary": "Login to Console",
        "operationId": "Login",
        "parameters": [
          {
            "type": "string",
            "name": "password",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "apiKey",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "insecure",
            "in": "formData"
          },
          {
            "type": "file",
            "name": "cert",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "key",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "A successful login."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/logout": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Logout from Console.",
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/session": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Endpoint to check if your session is still valid",
        "operationId": "SessionCheck",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/sessionResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "encryptionAPI": {
      "type": "object",
      "properties": {
        "maxBody": {
          "type": "integer"
        },
        "method": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "timeout": {
          "type": "integer"
        }
      }
    },
    "encryptionAPIsResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionAPI"
          }
        }
      }
    },
    "encryptionAssignPolicyRequest": {
      "type": "object",
      "properties": {
        "identity": {
          "type": "string"
        }
      }
    },
    "encryptionCreateKeyRequest": {
      "type": "object",
      "required": [
        "key"
      ],
      "properties": {
        "key": {
          "type": "string"
        }
      }
    },
    "encryptionDeleteKeyRequest": {
      "type": "object"
    },
    "encryptionDescribeIdentityResponse": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "identity": {
          "type": "string"
        },
        "policy": {
          "type": "string"
        }
      }
    },
    "encryptionDescribeKeyResponse": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "string"
        },
        "algorithm": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionDescribePolicyResponse": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionDescribeSelfIdentityResponse": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "identity": {
          "type": "string"
        },
        "policy": {
          "$ref": "#/definitions/encryptionGetPolicyResponse"
        },
        "policyName": {
          "type": "string"
        }
      }
    },
    "encryptionEndpoint": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "encryptionGetPolicyResponse": {
      "type": "object",
      "properties": {
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deny": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "encryptionIdentityInfo": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "identity": {
          "type": "string"
        },
        "isAdmin": {
          "type": "boolean"
        },
        "policy": {
          "type": "string"
        }
      }
    },
    "encryptionImportKeyRequest": {
      "type": "object",
      "required": [
        "bytes"
      ],
      "properties": {
        "bytes": {
          "type": "string"
        }
      }
    },
    "encryptionKeyInfo": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionLatencyHistogram": {
      "type": "object",
      "properties": {
        "duration": {
          "type": "integer"
        },
        "total": {
          "type": "integer"
        }
      }
    },
    "encryptionListIdentitiesResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionIdentityInfo"
          }
        }
      }
    },
    "encryptionListKeysResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionKeyInfo"
          }
        }
      }
    },
    "encryptionListPoliciesResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionPolicyInfo"
          }
        }
      }
    },
    "encryptionMetricsResponse": {
      "type": "object",
      "required": [
        "requestOK",
        "requestErr",
        "requestFail",
        "requestActive",
        "auditEvents",
        "errorEvents",
        "latencyHistogram",
        "uptime",
        "cpus",
        "usableCPUs",
        "threads",
        "heapAlloc",
        "stackAlloc"
      ],
      "properties": {
        "auditEvents": {
          "type": "integer"
        },
        "cpus": {
          "type": "integer"
        },
        "errorEvents": {
          "type": "integer"
        },
        "heapAlloc": {
          "type": "integer"
        },
        "heapObjects": {
          "type": "integer"
        },
        "latencyHistogram": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionLatencyHistogram"
          }
        },
        "requestActive": {
          "type": "integer"
        },
        "requestErr": {
          "type": "integer"
        },
        "requestFail": {
          "type": "integer"
        },
        "requestOK": {
          "type": "integer"
        },
        "stackAlloc": {
          "type": "integer"
        },
        "threads": {
          "type": "integer"
        },
        "uptime": {
          "type": "integer"
        },
        "usableCPUs": {
          "type": "integer"
        }
      }
    },
    "encryptionPolicyInfo": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionSetPolicyRequest": {
      "type": "object",
      "required": [
        "policy"
      ],
      "properties": {
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deny": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "policy": {
          "type": "string"
        }
      }
    },
    "encryptionStatusResponse": {
      "type": "object",
      "properties": {
        "defaultKeyID": {
          "type": "string"
        },
        "endpoints": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionEndpoint"
          }
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionVersionResponse": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message",
        "detailedMessage"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "detailedMessage": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "loginDetails": {
      "type": "object",
      "properties": {
        "loginStrategy": {
          "type": "string",
          "enum": [
            "form"
          ]
        },
        "redirectRules": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/redirectRule"
          }
        }
      }
    },
    "loginResponse": {
      "type": "object",
      "properties": {
        "IDPRefreshToken": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        }
      }
    },
    "logoutRequest": {
      "type": "object",
      "properties": {
        "state": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "object",
      "properties": {
        "clientCertificate": {
          "type": "string"
        },
        "clientKey": {
          "type": "string"
        },
        "insecure": {
          "type": "boolean"
        }
      }
    },
    "redirectRule": {
      "type": "object",
      "properties": {
        "displayName": {
          "type": "string"
        },
        "redirect": {
          "type": "string"
        }
      }
    },
    "sessionResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "ok"
          ]
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "http://min.io",
      "tokenUrl": "http://min.io"
    }
  },
  "security": [
    {
      "key": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "ws"
  ],
  "swagger": "2.0",
  "info": {
    "title": "MinIO KES",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/encryption/apis": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption apis",
        "operationId": "APIs",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionAPIsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/describe-self/identity": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe self identity",
        "operationId": "DescribeSelfIdentity",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribeSelfIdentityResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/identities": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption list identities",
        "operationId": "ListIdentities",
        "parameters": [
          {
            "type": "string",
            "description": "pattern to retrieve identities",
            "name": "pattern",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionListIdentitiesResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/identities/{name}": {
      "delete": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption delete identity",
        "operationId": "DeleteIdentity",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption identity name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/identities/{name}/describe": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe identity",
        "operationId": "DescribeIdentity",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption identity name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribeIdentityResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/keys": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption list keys",
        "operationId": "ListKeys",
        "parameters": [
          {
            "type": "string",
            "description": "pattern to retrieve keys",
            "name": "pattern",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionListKeysResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption create key",
        "operationId": "CreateKey",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionCreateKeyRequest"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/keys/{name}": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe key",
        "operationId": "DescribeKey",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption key name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribeKeyResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption delete key",
        "operationId": "DeleteKey",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption key name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/keys/{name}/import": {
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption import key",
        "operationId": "ImportKey",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionImportKeyRequest"
            }
          },
          {
            "type": "string",
            "description": "Encryption key name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "201": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/metrics": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption metrics",
        "operationId": "Metrics",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionMetricsResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption list policies",
        "operationId": "ListPolicies",
        "parameters": [
          {
            "type": "string",
            "description": "pattern to retrieve policies",
            "name": "pattern",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionListPoliciesResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption set policy",
        "operationId": "SetPolicy",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionSetPolicyRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies/{name}": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption get policy",
        "operationId": "GetPolicy",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionGetPolicyResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption delete policy",
        "operationId": "DeletePolicy",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies/{name}/assign": {
      "post": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption assign policy",
        "operationId": "AssignPolicy",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/encryptionAssignPolicyRequest"
            }
          },
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/policies/{name}/describe": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption describe policy",
        "operationId": "DescribePolicy",
        "parameters": [
          {
            "type": "string",
            "description": "Encryption policy name",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionDescribePolicyResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/status": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption status",
        "operationId": "Status",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionStatusResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/encryption/version": {
      "get": {
        "tags": [
          "Encryption"
        ],
        "summary": "Encryption version",
        "operationId": "Version",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/encryptionVersionResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/login": {
      "get": {
        "security": [],
        "tags": [
          "Auth"
        ],
        "summary": "Returns login strategy, form or sso.",
        "operationId": "LoginDetail",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/loginDetails"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "multipart/form-data"
        ],
        "tags": [
          "Auth"
        ],
        "summary": "Login to Console",
        "operationId": "Login",
        "parameters": [
          {
            "type": "string",
            "name": "password",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "apiKey",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "insecure",
            "in": "formData"
          },
          {
            "type": "file",
            "name": "cert",
            "in": "formData",
            "required": true
          },
          {
            "type": "file",
            "name": "key",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "A successful login."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/logout": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Logout from Console.",
        "operationId": "Logout",
        "responses": {
          "200": {
            "description": "A successful response."
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/session": {
      "get": {
        "tags": [
          "Auth"
        ],
        "summary": "Endpoint to check if your session is still valid",
        "operationId": "SessionCheck",
        "responses": {
          "200": {
            "description": "A successful response.",
            "schema": {
              "$ref": "#/definitions/sessionResponse"
            }
          },
          "default": {
            "description": "Generic error response.",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "encryptionAPI": {
      "type": "object",
      "properties": {
        "maxBody": {
          "type": "integer"
        },
        "method": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "timeout": {
          "type": "integer"
        }
      }
    },
    "encryptionAPIsResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionAPI"
          }
        }
      }
    },
    "encryptionAssignPolicyRequest": {
      "type": "object",
      "properties": {
        "identity": {
          "type": "string"
        }
      }
    },
    "encryptionCreateKeyRequest": {
      "type": "object",
      "required": [
        "key"
      ],
      "properties": {
        "key": {
          "type": "string"
        }
      }
    },
    "encryptionDeleteKeyRequest": {
      "type": "object"
    },
    "encryptionDescribeIdentityResponse": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "identity": {
          "type": "string"
        },
        "policy": {
          "type": "string"
        }
      }
    },
    "encryptionDescribeKeyResponse": {
      "type": "object",
      "properties": {
        "ID": {
          "type": "string"
        },
        "algorithm": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionDescribePolicyResponse": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionDescribeSelfIdentityResponse": {
      "type": "object",
      "properties": {
        "admin": {
          "type": "boolean"
        },
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "identity": {
          "type": "string"
        },
        "policy": {
          "$ref": "#/definitions/encryptionGetPolicyResponse"
        },
        "policyName": {
          "type": "string"
        }
      }
    },
    "encryptionEndpoint": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "encryptionGetPolicyResponse": {
      "type": "object",
      "properties": {
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deny": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "encryptionIdentityInfo": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "identity": {
          "type": "string"
        },
        "isAdmin": {
          "type": "boolean"
        },
        "policy": {
          "type": "string"
        }
      }
    },
    "encryptionImportKeyRequest": {
      "type": "object",
      "required": [
        "bytes"
      ],
      "properties": {
        "bytes": {
          "type": "string"
        }
      }
    },
    "encryptionKeyInfo": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionLatencyHistogram": {
      "type": "object",
      "properties": {
        "duration": {
          "type": "integer"
        },
        "total": {
          "type": "integer"
        }
      }
    },
    "encryptionListIdentitiesResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionIdentityInfo"
          }
        }
      }
    },
    "encryptionListKeysResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionKeyInfo"
          }
        }
      }
    },
    "encryptionListPoliciesResponse": {
      "type": "object",
      "properties": {
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionPolicyInfo"
          }
        }
      }
    },
    "encryptionMetricsResponse": {
      "type": "object",
      "required": [
        "requestOK",
        "requestErr",
        "requestFail",
        "requestActive",
        "auditEvents",
        "errorEvents",
        "latencyHistogram",
        "uptime",
        "cpus",
        "usableCPUs",
        "threads",
        "heapAlloc",
        "stackAlloc"
      ],
      "properties": {
        "auditEvents": {
          "type": "integer"
        },
        "cpus": {
          "type": "integer"
        },
        "errorEvents": {
          "type": "integer"
        },
        "heapAlloc": {
          "type": "integer"
        },
        "heapObjects": {
          "type": "integer"
        },
        "latencyHistogram": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionLatencyHistogram"
          }
        },
        "requestActive": {
          "type": "integer"
        },
        "requestErr": {
          "type": "integer"
        },
        "requestFail": {
          "type": "integer"
        },
        "requestOK": {
          "type": "integer"
        },
        "stackAlloc": {
          "type": "integer"
        },
        "threads": {
          "type": "integer"
        },
        "uptime": {
          "type": "integer"
        },
        "usableCPUs": {
          "type": "integer"
        }
      }
    },
    "encryptionPolicyInfo": {
      "type": "object",
      "properties": {
        "createdAt": {
          "type": "string"
        },
        "createdBy": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionSetPolicyRequest": {
      "type": "object",
      "required": [
        "policy"
      ],
      "properties": {
        "allow": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "deny": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "policy": {
          "type": "string"
        }
      }
    },
    "encryptionStatusResponse": {
      "type": "object",
      "properties": {
        "defaultKeyID": {
          "type": "string"
        },
        "endpoints": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/encryptionEndpoint"
          }
        },
        "name": {
          "type": "string"
        }
      }
    },
    "encryptionVersionResponse": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message",
        "detailedMessage"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "detailedMessage": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "loginDetails": {
      "type": "object",
      "properties": {
        "loginStrategy": {
          "type": "string",
          "enum": [
            "form"
          ]
        },
        "redirectRules": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/redirectRule"
          }
        }
      }
    },
    "loginResponse": {
      "type": "object",
      "properties": {
        "IDPRefreshToken": {
          "type": "string"
        },
        "sessionId": {
          "type": "string"
        }
      }
    },
    "logoutRequest": {
      "type": "object",
      "properties": {
        "state": {
          "type": "string"
        }
      }
    },
    "principal": {
      "type": "object",
      "properties": {
        "clientCertificate": {
          "type": "string"
        },
        "clientKey": {
          "type": "string"
        },
        "insecure": {
          "type": "boolean"
        }
      }
    },
    "redirectRule": {
      "type": "object",
      "properties": {
        "displayName": {
          "type": "string"
        },
        "redirect": {
          "type": "string"
        }
      }
    },
    "sessionResponse": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string",
          "enum": [
            "ok"
          ]
        }
      }
    }
  },
  "securityDefinitions": {
    "key": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "http://min.io",
      "tokenUrl": "http://min.io"
    }
  },
  "security": [
    {
      "key": []
    }
  ]
}`))
}
