// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// APIsOKCode is the HTTP code returned for type APIsOK
const APIsOKCode int = 200

/*
APIsOK A successful response.

swagger:response aPIsOK
*/
type APIsOK struct {

	/*
	  In: Body
	*/
	Payload *models.EncryptionAPIsResponse `json:"body,omitempty"`
}

// NewAPIsOK creates APIsOK with default headers values
func NewAPIsOK() *APIsOK {

	return &APIsOK{}
}

// WithPayload adds the payload to the a p is o k response
func (o *APIsOK) WithPayload(payload *models.EncryptionAPIsResponse) *APIsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the a p is o k response
func (o *APIsOK) SetPayload(payload *models.EncryptionAPIsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *APIsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
APIsDefault Generic error response.

swagger:response aPIsDefault
*/
type APIsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAPIsDefault creates APIsDefault with default headers values
func NewAPIsDefault(code int) *APIsDefault {
	if code <= 0 {
		code = 500
	}

	return &APIsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the a p is default response
func (o *APIsDefault) WithStatusCode(code int) *APIsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the a p is default response
func (o *APIsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the a p is default response
func (o *APIsDefault) WithPayload(payload *models.Error) *APIsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the a p is default response
func (o *APIsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *APIsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
