// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// AssignPolicyOKCode is the HTTP code returned for type AssignPolicyOK
const AssignPolicyOKCode int = 200

/*
AssignPolicyOK A successful response.

swagger:response assignPolicyOK
*/
type AssignPolicyOK struct {
}

// NewAssignPolicyOK creates AssignPolicyOK with default headers values
func NewAssignPolicyOK() *AssignPolicyOK {

	return &AssignPolicyOK{}
}

// WriteResponse to the client
func (o *AssignPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
AssignPolicyDefault Generic error response.

swagger:response assignPolicyDefault
*/
type AssignPolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAssignPolicyDefault creates AssignPolicyDefault with default headers values
func NewAssignPolicyDefault(code int) *AssignPolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &AssignPolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the assign policy default response
func (o *AssignPolicyDefault) WithStatusCode(code int) *AssignPolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the assign policy default response
func (o *AssignPolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the assign policy default response
func (o *AssignPolicyDefault) WithPayload(payload *models.Error) *AssignPolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the assign policy default response
func (o *AssignPolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AssignPolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
