// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// CreateKeyCreatedCode is the HTTP code returned for type CreateKeyCreated
const CreateKeyCreatedCode int = 201

/*
CreateKeyCreated A successful response.

swagger:response createKeyCreated
*/
type CreateKeyCreated struct {
}

// NewCreateKeyCreated creates CreateKeyCreated with default headers values
func NewCreateKeyCreated() *CreateKeyCreated {

	return &CreateKeyCreated{}
}

// WriteResponse to the client
func (o *CreateKeyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*
CreateKeyDefault Generic error response.

swagger:response createKeyDefault
*/
type CreateKeyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateKeyDefault creates CreateKeyDefault with default headers values
func NewCreateKeyDefault(code int) *CreateKeyDefault {
	if code <= 0 {
		code = 500
	}

	return &CreateKeyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the create key default response
func (o *CreateKeyDefault) WithStatusCode(code int) *CreateKeyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the create key default response
func (o *CreateKeyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the create key default response
func (o *CreateKeyDefault) WithPayload(payload *models.Error) *CreateKeyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create key default response
func (o *CreateKeyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateKeyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
