// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// DescribeKeyOKCode is the HTTP code returned for type DescribeKeyOK
const DescribeKeyOKCode int = 200

/*
DescribeKeyOK A successful response.

swagger:response describeKeyOK
*/
type DescribeKeyOK struct {

	/*
	  In: Body
	*/
	Payload *models.EncryptionDescribeKeyResponse `json:"body,omitempty"`
}

// NewDescribeKeyOK creates DescribeKeyOK with default headers values
func NewDescribeKeyOK() *DescribeKeyOK {

	return &DescribeKeyOK{}
}

// WithPayload adds the payload to the describe key o k response
func (o *DescribeKeyOK) WithPayload(payload *models.EncryptionDescribeKeyResponse) *DescribeKeyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the describe key o k response
func (o *DescribeKeyOK) SetPayload(payload *models.EncryptionDescribeKeyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DescribeKeyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DescribeKeyDefault Generic error response.

swagger:response describeKeyDefault
*/
type DescribeKeyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDescribeKeyDefault creates DescribeKeyDefault with default headers values
func NewDescribeKeyDefault(code int) *DescribeKeyDefault {
	if code <= 0 {
		code = 500
	}

	return &DescribeKeyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the describe key default response
func (o *DescribeKeyDefault) WithStatusCode(code int) *DescribeKeyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the describe key default response
func (o *DescribeKeyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the describe key default response
func (o *DescribeKeyDefault) WithPayload(payload *models.Error) *DescribeKeyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the describe key default response
func (o *DescribeKeyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DescribeKeyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
