// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// DescribePolicyOKCode is the HTTP code returned for type DescribePolicyOK
const DescribePolicyOKCode int = 200

/*
DescribePolicyOK A successful response.

swagger:response describePolicyOK
*/
type DescribePolicyOK struct {

	/*
	  In: Body
	*/
	Payload *models.EncryptionDescribePolicyResponse `json:"body,omitempty"`
}

// NewDescribePolicyOK creates DescribePolicyOK with default headers values
func NewDescribePolicyOK() *DescribePolicyOK {

	return &DescribePolicyOK{}
}

// WithPayload adds the payload to the describe policy o k response
func (o *DescribePolicyOK) WithPayload(payload *models.EncryptionDescribePolicyResponse) *DescribePolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the describe policy o k response
func (o *DescribePolicyOK) SetPayload(payload *models.EncryptionDescribePolicyResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DescribePolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
DescribePolicyDefault Generic error response.

swagger:response describePolicyDefault
*/
type DescribePolicyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDescribePolicyDefault creates DescribePolicyDefault with default headers values
func NewDescribePolicyDefault(code int) *DescribePolicyDefault {
	if code <= 0 {
		code = 500
	}

	return &DescribePolicyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the describe policy default response
func (o *DescribePolicyDefault) WithStatusCode(code int) *DescribePolicyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the describe policy default response
func (o *DescribePolicyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the describe policy default response
func (o *DescribePolicyDefault) WithPayload(payload *models.Error) *DescribePolicyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the describe policy default response
func (o *DescribePolicyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DescribePolicyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
