// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// ImportKeyCreatedCode is the HTTP code returned for type ImportKeyCreated
const ImportKeyCreatedCode int = 201

/*
ImportKeyCreated A successful response.

swagger:response importKeyCreated
*/
type ImportKeyCreated struct {
}

// NewImportKeyCreated creates ImportKeyCreated with default headers values
func NewImportKeyCreated() *ImportKeyCreated {

	return &ImportKeyCreated{}
}

// WriteResponse to the client
func (o *ImportKeyCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*
ImportKeyDefault Generic error response.

swagger:response importKeyDefault
*/
type ImportKeyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewImportKeyDefault creates ImportKeyDefault with default headers values
func NewImportKeyDefault(code int) *ImportKeyDefault {
	if code <= 0 {
		code = 500
	}

	return &ImportKeyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the import key default response
func (o *ImportKeyDefault) WithStatusCode(code int) *ImportKeyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the import key default response
func (o *ImportKeyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the import key default response
func (o *ImportKeyDefault) WithPayload(payload *models.Error) *ImportKeyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the import key default response
func (o *ImportKeyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ImportKeyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
