// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// KeyStatusOKCode is the HTTP code returned for type KeyStatusOK
const KeyStatusOKCode int = 200

/*
KeyStatusOK A successful response.

swagger:response keyStatusOK
*/
type KeyStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.EncryptionKeyStatusResponse `json:"body,omitempty"`
}

// NewKeyStatusOK creates KeyStatusOK with default headers values
func NewKeyStatusOK() *KeyStatusOK {

	return &KeyStatusOK{}
}

// WithPayload adds the payload to the key status o k response
func (o *KeyStatusOK) WithPayload(payload *models.EncryptionKeyStatusResponse) *KeyStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the key status o k response
func (o *KeyStatusOK) SetPayload(payload *models.EncryptionKeyStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KeyStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
KeyStatusDefault Generic error response.

swagger:response keyStatusDefault
*/
type KeyStatusDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewKeyStatusDefault creates KeyStatusDefault with default headers values
func NewKeyStatusDefault(code int) *KeyStatusDefault {
	if code <= 0 {
		code = 500
	}

	return &KeyStatusDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the key status default response
func (o *KeyStatusDefault) WithStatusCode(code int) *KeyStatusDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the key status default response
func (o *KeyStatusDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the key status default response
func (o *KeyStatusDefault) WithPayload(payload *models.Error) *KeyStatusDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the key status default response
func (o *KeyStatusDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *KeyStatusDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
