// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// ListIdentitiesOKCode is the HTTP code returned for type ListIdentitiesOK
const ListIdentitiesOKCode int = 200

/*
ListIdentitiesOK A successful response.

swagger:response listIdentitiesOK
*/
type ListIdentitiesOK struct {

	/*
	  In: Body
	*/
	Payload *models.EncryptionListIdentitiesResponse `json:"body,omitempty"`
}

// NewListIdentitiesOK creates ListIdentitiesOK with default headers values
func NewListIdentitiesOK() *ListIdentitiesOK {

	return &ListIdentitiesOK{}
}

// WithPayload adds the payload to the list identities o k response
func (o *ListIdentitiesOK) WithPayload(payload *models.EncryptionListIdentitiesResponse) *ListIdentitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list identities o k response
func (o *ListIdentitiesOK) SetPayload(payload *models.EncryptionListIdentitiesResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListIdentitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ListIdentitiesDefault Generic error response.

swagger:response listIdentitiesDefault
*/
type ListIdentitiesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListIdentitiesDefault creates ListIdentitiesDefault with default headers values
func NewListIdentitiesDefault(code int) *ListIdentitiesDefault {
	if code <= 0 {
		code = 500
	}

	return &ListIdentitiesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list identities default response
func (o *ListIdentitiesDefault) WithStatusCode(code int) *ListIdentitiesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list identities default response
func (o *ListIdentitiesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list identities default response
func (o *ListIdentitiesDefault) WithPayload(payload *models.Error) *ListIdentitiesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list identities default response
func (o *ListIdentitiesDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListIdentitiesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
