// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// ListSecretsOKCode is the HTTP code returned for type ListSecretsOK
const ListSecretsOKCode int = 200

/*
ListSecretsOK A successful response.

swagger:response listSecretsOK
*/
type ListSecretsOK struct {

	/*
	  In: Body
	*/
	Payload *models.EncryptionListSecretsResponse `json:"body,omitempty"`
}

// NewListSecretsOK creates ListSecretsOK with default headers values
func NewListSecretsOK() *ListSecretsOK {

	return &ListSecretsOK{}
}

// WithPayload adds the payload to the list secrets o k response
func (o *ListSecretsOK) WithPayload(payload *models.EncryptionListSecretsResponse) *ListSecretsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list secrets o k response
func (o *ListSecretsOK) SetPayload(payload *models.EncryptionListSecretsResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSecretsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
ListSecretsDefault Generic error response.

swagger:response listSecretsDefault
*/
type ListSecretsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListSecretsDefault creates ListSecretsDefault with default headers values
func NewListSecretsDefault(code int) *ListSecretsDefault {
	if code <= 0 {
		code = 500
	}

	return &ListSecretsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list secrets default response
func (o *ListSecretsDefault) WithStatusCode(code int) *ListSecretsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list secrets default response
func (o *ListSecretsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list secrets default response
func (o *ListSecretsDefault) WithPayload(payload *models.Error) *ListSecretsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list secrets default response
func (o *ListSecretsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListSecretsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
