// Code generated by go-swagger; DO NOT EDIT.

// This file is part of MinIO KES
// Copyright (c) 2023 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package encryption

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/minio/kes/models"
)

// StatusOKCode is the HTTP code returned for type StatusOK
const StatusOKCode int = 200

/*
StatusOK A successful response.

swagger:response statusOK
*/
type StatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.EncryptionStatusResponse `json:"body,omitempty"`
}

// NewStatusOK creates StatusOK with default headers values
func NewStatusOK() *StatusOK {

	return &StatusOK{}
}

// WithPayload adds the payload to the status o k response
func (o *StatusOK) WithPayload(payload *models.EncryptionStatusResponse) *StatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status o k response
func (o *StatusOK) SetPayload(payload *models.EncryptionStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
StatusDefault Generic error response.

swagger:response statusDefault
*/
type StatusDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStatusDefault creates StatusDefault with default headers values
func NewStatusDefault(code int) *StatusDefault {
	if code <= 0 {
		code = 500
	}

	return &StatusDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the status default response
func (o *StatusDefault) WithStatusCode(code int) *StatusDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the status default response
func (o *StatusDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the status default response
func (o *StatusDefault) WithPayload(payload *models.Error) *StatusDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the status default response
func (o *StatusDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StatusDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
