name: Commit

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  single:
    name: "Require that there is only one commit"
    runs-on: ubuntu-latest
    steps:
      - run: |
           echo ${{ github.event.head_commit.message }}
           [[ ${{ github.event.commits[1].message }} == null ]] || exit 1;
