name: edge tests

on:
  push:
    branches:
    - master

jobs:
  aws-edge-test:
    name: Test AWS edge
    runs-on: [self-hosted,minio-pg1]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.5
        check-latest: true
      id: go
    - name: Check out code
      uses: actions/checkout@v3
    - name: Test
      env:
        GO111MODULE: on
      run: |
         cd ./edge
         go test -v -aws.config=/etc/kes/config-aws.yml -run="TestAWS"
  azure-edge-test:
    name: Test Azure edge
    runs-on: [self-hosted,minio-pg1]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.5
        check-latest: true
      id: go
    - name: Check out code
      uses: actions/checkout@v3
    - name: Test
      env:
        GO111MODULE: on
      run: |
         cd ./edge
         go test -v -azure.config=/etc/kes/config-azure.yml -run="TestAzure"
