name: VulnCheck
on:
  pull_request:
    branches:
    - master
    - main
  push:
    branches:
    - master
    - main
jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.2
        check-latest: true
    - name: Get govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
      shell: bash
    - name: Run govulncheck
      run: govulncheck ./...
      shell: bash
